FROM node:20 AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
RUN npm run build

# Serve using nginx
FROM nginx:stable
COPY --from=build /app/dist /usr/share/nginx/html
