services:
  backend:
    image: pcheol/barunchuck-backend
    container_name: barunchuck-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    environment:
      - NODE_ENV=production
    networks:
      - barunchuck-network

  frontend:
    image: pcheol/barunchuck-frontend
    container_name: barunchuck-frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - barunchuck-network

networks:
  barunchuck-network:
    driver: bridge
