version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend/uploadedFiles:/app/uploadedFiles
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    image: nginx:stable
    ports:
      - "5173:5173"
    depends_on:
      - backend
